<a href="https://colab.research.google.com/github/Somesh140/Transformers/blob/main/Transformers_Tokeniser.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
%cd /content/drive/MyDrive/Classes/Transformers

/content/drive/MyDrive/Classes/Transformers


In [5]:

try :
  from transformers import pipeline
except Exception as e:
    print(e)
    print("Installing.....")
    !pip install datasets transformers[sentencepiece] -q
    from transformers import pipeline

No module named 'transformers'
Installing.....
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 486.2/486.2 kB 23.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 93.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 12.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.5/212.5 kB 24.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.3/134.3 kB 17.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 67.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 236.8/236.8 kB 22.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 84.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 73.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 71.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 kB 13.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 30.8 MB/s eta

In [6]:
model_name = "bert-base-cased"

In [7]:
from transformers import BertTokenizer, AutoTokenizer

In [8]:
tokenizer = BertTokenizer.from_pretrained(model_name)

In [9]:
example = "Transformers is an interesting library"

In [10]:
tokenizer(example)

{'input_ids': [101, 25267, 1110, 1126, 5426, 3340, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1]}

In [11]:
autotokenizer=AutoTokenizer.from_pretrained(model_name)

In [12]:
autotokenizer(example)

{'input_ids': [101, 25267, 1110, 1126, 5426, 3340, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1]}

In [13]:
tokenizer.save_pretrained("./sample_tokenizer")

('./sample_tokenizer/tokenizer_config.json',
 './sample_tokenizer/special_tokens_map.json',
 './sample_tokenizer/vocab.txt',
 './sample_tokenizer/added_tokens.json')

In [15]:
load_tokenizer = AutoTokenizer.from_pretrained("./sample_tokenizer")

In [16]:
load_tokenizer(example)

{'input_ids': [101, 25267, 1110, 1126, 5426, 3340, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1]}

In [17]:
autotokenizer.tokenize(example)

['Transformers', 'is', 'an', 'interesting', 'library']

In [19]:
tokens = tokenizer.tokenize(example)
tokens

['Transformers', 'is', 'an', 'interesting', 'library']

In [22]:
ids = tokenizer.convert_tokens_to_ids(tokens)
ids

[25267, 1110, 1126, 5426, 3340]

In [23]:
tokenizer.convert_ids_to_tokens(ids)

['Transformers', 'is', 'an', 'interesting', 'library']

In [24]:
updated_ids = [101, 25267, 1110, 1126, 5426, 3340, 102]
tokenizer.convert_ids_to_tokens(updated_ids)

['[CLS]', 'Transformers', 'is', 'an', 'interesting', 'library', '[SEP]']

In [25]:
tokenizer.decode(updated_ids)

'[CLS] Transformers is an interesting library [SEP]'

# Handling multiple sequences

In [14]:
import torch
from transformers import AutoTokenizer,AutoModelForSequenceClassification

In [15]:
ckpt = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(ckpt)

In [16]:
model = AutoModelForSequenceClassification.from_pretrained(ckpt)

In [17]:
example ="I' ve  been exploring Transformers for Natural Language Processing"

In [18]:
tokens =  tokenizer.tokenize(example)
ids = tokenizer.convert_tokens_to_ids(tokens)
input_ids = torch.tensor(ids)


In [19]:
model(input_ids) # it will throw error

RuntimeError: ignored

In [20]:
# you can do this
torch.unsqueeze(input_ids, dim=0) # in this input_id there is no starting and ending tag

tensor([[ 1045,  1005,  2310,  2042, 11131, 19081,  2005,  3019,  2653,  6364]])

In [21]:
model(torch.unsqueeze(input_ids, dim=0))

SequenceClassifierOutput(loss=None, logits=tensor([[ 1.0319, -0.8272]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [22]:
tokenized_inputs = tokenizer(example, return_tensors='pt')

In [23]:
tokenized_inputs["input_ids"]

tensor([[  101,  1045,  1005,  2310,  2042, 11131, 19081,  2005,  3019,  2653,
          6364,   102]])

In [24]:
model(tokenized_inputs["input_ids"])

SequenceClassifierOutput(loss=None, logits=tensor([[-0.3594,  0.4591]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [25]:
tokenizer.pad_token_id

0

In [31]:
example_1 = "I've been exploring Transformers for Natural Language Processing."
example_2 = "I've been exploring Transformers."

In [32]:
token_1 = tokenizer.tokenize(example_1)
print(token_1)
token_2 = tokenizer.tokenize(example_2)
print(token_2)

['i', "'", 've', 'been', 'exploring', 'transformers', 'for', 'natural', 'language', 'processing', '.']
['i', "'", 've', 'been', 'exploring', 'transformers', '.']


In [33]:
id_1 = tokenizer.convert_tokens_to_ids(token_1)
id_2 = tokenizer.convert_tokens_to_ids(token_2)

In [34]:
batch_id = [
    id_1,
    id_2
]
batch_id


[[1045, 1005, 2310, 2042, 11131, 19081, 2005, 3019, 2653, 6364, 1012],
 [1045, 1005, 2310, 2042, 11131, 19081, 1012]]

In [35]:
len(id_1)

11

In [36]:
len(id_2)

7

In [37]:
model(torch.tensor([id_1])).logits

tensor([[ 0.9019, -0.6752]], grad_fn=<AddmmBackward0>)

In [38]:
model(torch.tensor(batch_id))

ValueError: ignored

In [42]:
batch_id

[[1045, 1005, 2310, 2042, 11131, 19081, 2005, 3019, 2653, 6364, 1012],
 [1045, 1005, 2310, 2042, 11131, 19081, 1012, 0, 0, 0, 0]]

In [39]:
max_len = 11

while  len(id_2)!= max_len:
  id_2.append(tokenizer.pad_token_id)

In [41]:
model(torch.tensor(batch_id)).logits

tensor([[ 0.9019, -0.6752],
        [ 0.7740, -0.6163]], grad_fn=<AddmmBackward0>)

In [43]:
attention_mask = [
                  [1]*11,
                  [1]*7 + [0]*4
]
attention_mask

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]]

In [44]:
model(
    torch.tensor(batch_id),
    attention_mask=torch.tensor(attention_mask)
    ).logits

tensor([[ 0.9019, -0.6752],
        [-0.5456,  0.7677]], grad_fn=<AddmmBackward0>)