<a href="https://colab.research.google.com/github/Somesh140/Transformers/blob/main/Transformers_002basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:

%cd /content/drive/MyDrive/Classes/Transformers

/content/drive/MyDrive/Classes/Transformers


In [3]:
try :
  from transformers import pipeline
except Exception as e:
    print(e)
    print("Installing.....")
    !pip install datasets transformers[sentencepiece] -q
    from transformers import pipeline

No module named 'transformers'
Installing.....
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.6/485.6 kB 14.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 61.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 13.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.5/212.5 kB 22.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.3/134.3 kB 13.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 59.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 236.8/236.8 kB 22.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 66.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 64.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 65.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 kB 14.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 31.0 MB/s eta

In [6]:
from transformers import AutoTokenizer

In [7]:
ckpt= "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(ckpt)

In [8]:
inputs = "resident Joe Biden may raise US concerns about human rights during his talks with Prime Minister Narendra Modi. However, Biden will not “lecture” the Indian leader, who is on a state visit, on the issue of democracy, according to White House National Security Adviser Jake Sullivan.PM Modi is scheduled to hold high-level talks with President Biden on Thursday during which the two leaders are expected to discuss a wide range of issues of mutual and global interests."

In [9]:
tokenizer(inputs)

{'input_ids': [101, 6319, 3533, 7226, 2368, 2089, 5333, 2149, 5936, 2055, 2529, 2916, 2076, 2010, 7566, 2007, 3539, 2704, 6583, 7389, 7265, 16913, 2072, 1012, 2174, 1010, 7226, 2368, 2097, 2025, 1523, 8835, 1524, 1996, 2796, 3003, 1010, 2040, 2003, 2006, 1037, 2110, 3942, 1010, 2006, 1996, 3277, 1997, 7072, 1010, 2429, 2000, 2317, 2160, 2120, 3036, 11747, 5180, 7624, 1012, 7610, 16913, 2072, 2003, 5115, 2000, 2907, 2152, 1011, 2504, 7566, 2007, 2343, 7226, 2368, 2006, 9432, 2076, 2029, 1996, 2048, 4177, 2024, 3517, 2000, 6848, 1037, 2898, 2846, 1997, 3314, 1997, 8203, 1998, 3795, 5426, 1012, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [12]:
batch_input = ["I love my country", "my name is Somesh Trivedi"]
tokenizer(batch_input, padding = True)

{'input_ids': [[101, 1045, 2293, 2026, 2406, 102, 0, 0, 0, 0], [101, 2026, 2171, 2003, 2070, 4095, 13012, 7178, 2072, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [13]:
out = tokenizer(batch_input, padding = True)

In [14]:
type(out)

transformers.tokenization_utils_base.BatchEncoding

In [18]:
out_pytorch_tensors = tokenizer(batch_input, padding= True, return_tensors = "pt")
out_pytorch_tensors

{'input_ids': tensor([[  101,  1045,  2293,  2026,  2406,   102,     0,     0,     0,     0],
        [  101,  2026,  2171,  2003,  2070,  4095, 13012,  7178,  2072,   102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [19]:
out_TF_tensors = tokenizer(batch_input, padding= True, return_tensors = "tf")
out_TF_tensors

{'input_ids': <tf.Tensor: shape=(2, 10), dtype=int32, numpy=
array([[  101,  1045,  2293,  2026,  2406,   102,     0,     0,     0,
            0],
       [  101,  2026,  2171,  2003,  2070,  4095, 13012,  7178,  2072,
          102]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 10), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [20]:
from transformers import AutoModel

In [21]:
model_ckpt = AutoModel.from_pretrained(ckpt)

Some weights of the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing DistilBertModel: ['pre_classifier.weight', 'classifier.weight', 'classifier.bias', 'pre_classifier.bias']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [22]:
model_ckpt

DistilBertModel(
  (embeddings): Embeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (transformer): Transformer(
    (layer): ModuleList(
      (0-5): 6 x TransformerBlock(
        (attention): MultiHeadSelfAttention(
          (dropout): Dropout(p=0.1, inplace=False)
          (q_lin): Linear(in_features=768, out_features=768, bias=True)
          (k_lin): Linear(in_features=768, out_features=768, bias=True)
          (v_lin): Linear(in_features=768, out_features=768, bias=True)
          (out_lin): Linear(in_features=768, out_features=768, bias=True)
        )
        (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        (ffn): FFN(
          (dropout): Dropout(p=0.1, inplace=False)
          (lin1): Linear(in_features=768, out_features=3072, bias=True)
          (lin2): Li

In [23]:
logits = model_ckpt(**out_pytorch_tensors)
logits

BaseModelOutput(last_hidden_state=tensor([[[ 0.4521,  0.2584,  0.0448,  ...,  0.4836,  0.8697, -0.2664],
         [ 0.5710,  0.4134,  0.0491,  ...,  0.5090,  0.7748, -0.2068],
         [ 0.8872,  0.5492,  0.2826,  ...,  0.3853,  0.8563, -0.2052],
         ...,
         [ 0.3523,  0.2676, -0.0041,  ...,  0.5652,  0.6715, -0.0517],
         [ 0.1845,  0.2399, -0.0395,  ...,  0.5929,  0.8065,  0.0323],
         [ 0.1293,  0.1981, -0.0614,  ...,  0.5446,  0.7708, -0.1253]],

        [[ 0.5225, -0.0376,  0.5346,  ...,  0.1383,  0.6709, -0.1563],
         [ 1.0321,  0.1842, -0.0354,  ...,  0.0547,  0.5509, -0.1937],
         [ 0.5879,  0.1844,  0.2600,  ..., -0.0192,  0.6043, -0.4758],
         ...,
         [ 0.5654, -0.6693,  0.8853,  ...,  0.1959,  0.7294,  0.4031],
         [ 0.3894, -0.5314,  0.2766,  ...,  0.5571,  0.7302, -0.3395],
         [ 0.9375, -0.0156,  0.3965,  ...,  0.6301, -0.0032, -0.5811]]],
       grad_fn=<NativeLayerNormBackward0>), hidden_states=None, attentions=None)

In [26]:
batch_size, sequence_len, Hidden_state = logits["last_hidden_state"].shape
batch_size, sequence_len, Hidden_state

(2, 10, 768)

In [29]:
from transformers import AutoModelForSequenceClassification
model_2 = AutoModelForSequenceClassification.from_pretrained(ckpt)
pred = model_2(**out_pytorch_tensors)
pred

SequenceClassifierOutput(loss=None, logits=tensor([[-4.2268,  4.5594],
        [-2.4240,  2.6357]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [30]:
import torch
pred_prob = torch.nn.functional.softmax(pred.logits, dim=1)
print(pred_prob)

tensor([[1.5280e-04, 9.9985e-01],
        [6.3071e-03, 9.9369e-01]], grad_fn=<SoftmaxBackward0>)


In [31]:
model_2.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [32]:
torch.argmax(pred_prob, dim=1)

tensor([1, 1])

In [33]:
from transformers import BertConfig, BertModel

In [34]:
config = BertConfig()
config

BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.30.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

In [35]:
model = BertModel(config) #This will create a model architecture with newly init weights


# model with trained weights

In [36]:
model_with_trained_wts = BertModel.from_pretrained("bert-base-cased")

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertModel: ['cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [37]:
model_with_trained_wts.save_pretrained("./model_dir")

In [38]:
seq =["Hello", "I ", "Somesh"]

In [39]:
encoded_sequences = [
    [101, 7592, 999, 102],
    [101, 4658, 1012, 102],
    [101, 3835, 999, 102]
]

In [40]:
model_ins = torch.tensor(encoded_sequences)

In [42]:
pred = model_with_trained_wts(model_ins)
pred

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 4.4496e-01,  4.8276e-01,  2.7797e-01,  ..., -5.4032e-02,
           3.9394e-01, -9.4770e-02],
         [ 2.4943e-01, -4.4093e-01,  8.1772e-01,  ..., -3.1917e-01,
           2.2992e-01, -4.1172e-02],
         [ 1.3668e-01,  2.2518e-01,  1.4502e-01,  ..., -4.6915e-02,
           2.8224e-01,  7.5566e-02],
         [ 1.1789e+00,  1.6738e-01, -1.8187e-01,  ...,  2.4671e-01,
           1.0441e+00, -6.1970e-03]],

        [[ 3.6436e-01,  3.2464e-02,  2.0258e-01,  ...,  6.0111e-02,
           3.2451e-01, -2.0995e-02],
         [ 7.1866e-01, -4.8725e-01,  5.1740e-01,  ..., -4.4012e-01,
           1.4553e-01, -3.7545e-02],
         [ 3.3223e-01, -2.3271e-01,  9.4877e-02,  ..., -2.5268e-01,
           3.2172e-01,  8.1079e-04],
         [ 1.2523e+00,  3.5754e-01, -5.1320e-02,  ..., -3.7840e-01,
           1.0526e+00, -5.6255e-01]],

        [[ 2.4042e-01,  1.4718e-01,  1.2110e-01,  ...,  7.6062e-02,
           3.3564e-01,  2